apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: paulopkl/go-without-install:v5
          envFrom:
            - configMapRef:
                name: goserver-env

          volumeMounts:
            - mountPath: "/usr/app/myfamily"
              name: config-volume
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
      