apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  # Pods
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: paulopkl/go-without-install:v4
          env:
            - name: NAME
              value: "Paulo"
            - name: AGE
              value: "20"