apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: LoadBalancer # ClusterIP, NodePort, LoadBalancer, HeadlessService
  ports:
    - name: goserver-service-port
      port: 80
      targetPort: 8080
      protocol: TCP
